# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Harold Dost's Blog
email: me@hdost.com
description: >
  This is a blog about the personal thoughts and feelings, sometimes
  even hard information from Harold Dost, SRE at Criteo SA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.harolddost.com" # the base hostname & protocol for your site
twitter_username: hdost
github_username:  hdost
linkedin_username: harolddost

# Build settings
markdown: kramdown

include:
  - .well-known
